In [2]:
import sys, os
sys.path.append(os.path.abspath('../..'))
from utlis.scan_engine_utlis.scan_engine_utlis import read_all_parquet_files

base_folder = "/data/big_rim/uploade_ssh_mir_dataset" # "/hpc/group/tdunn/Bryan_Rigs/BigOpenField/cleaned/oct3v1_social_mini"
all_df = read_all_parquet_files(base_folder)

In [5]:
import pyarrow.compute as pc
from functools import reduce


table = all_df #combined_df
# Filter mir_generate_param == 0 and sync != 3
# ============================================================================
# FILTERING CONDITIONS
# ============================================================================

# Define your filtering criteria
conditions = [
    
    pc.equal(table['social'], '0'),    # Solo recordings only (0=solo, 1=social)
    
]


filter_mask = reduce(pc.and_, conditions)


# Apply the filter and print the results
filtered_table = table.filter(filter_mask)

# ============================================================================
# DISPLAY RESULTS
# ============================================================================

# Convert to pandas for easier viewing
filtered_df = filtered_table.to_pandas()

# Select meaningful columns for display
display_cols = ['export_dest_rel_path', 'export_dest_full_path', 'social', 'test', 'before_oxytocin', 'after_oxytocin']

print(f"\nFiltered: {len(filtered_df)} recordings")
filtered_df[display_cols]

Filtered: 255 recordings

,export_dest_rel_path,export_dest_full_path,social,test,before_oxytocin,after_oxytocin
0,single/20241024_MC8_S1/,/data/big_rim/sorted_mir_dataset/oct3v1_single...,0,0,0,0
1,single/20241017_VC4_S3/,/data/big_rim/sorted_mir_dataset/oct3v1_single...,0,0,0,0
2,single/20241107_MC7_S3/,/data/big_rim/sorted_mir_dataset/oct3v1_single...,0,0,0,1
3,single/20250212_MC8_S3/,/data/big_rim/sorted_mir_dataset/oct3v1_single...,0,0,0,0
4,single/20250212_MC8_S5/,/data/big_rim/sorted_mir_dataset/oct3v1_single...,0,0,0,0
...,...,...,...,...,...,...
250,oct3v1_beh_only/single/20250213_MC16_S3/,/data/big_rim/uploade_ssh_mir_dataset/oct3v1_b...,0,0,0,0
251,oct3v1_beh_only/single/20241113_MC10_S1/,/data/big_rim/uploade_ssh_mir_dataset/oct3v1_b...,0,1,0,0
252,oct3v1_beh_only/single/20240918_VC19_S1/,/data/big_rim/uploade_ssh_mir_dataset/oct3v1_b...,0,0,0,0
253,oct3v1_beh_only/single/20241025_MC15_S2/,/data/big_rim/uploade_ssh_mir_dataset/oct3v1_b...,0,0,0,0
254,oct3v1_beh_only/single/20241008_VC4_S7/,/data/big_rim/uploade_ssh_mir_dataset/oct3v1_b...,0,0,0,0

In [ ]:
import os, sys
sys.path.append(os.path.abspath('../..'))
from utlis.sync_utlis.general_loader import load_flat_with_frame_map, merge_pred_with_miniscope
from utlis.sync_utlis.general_loader_viz import plot_two_coms_from_pred_df


oct3v1 = "/data/big_rim/rsync_dcc_sum/Oct3V1"
rec_path = os.path.join(oct3v1, "2024_10_31/2social_mini_20240819V1r1_femalebleach_11_48")
nc_key='wnd1500_stp700_max25_diff3.5_pnr1.1'
dannce_folder='SDANNCE/predict00'


# df = load_flat_with_frame_map(
#     rec_path,
#     pred_folder="SDANNCE/predict00",   # default
#     pred_filename="save_data_AVG.mat", # default
#     com_folder=None,                   # optional
#     kp_names=None,                     # or your 22 names
#     mapping_path=None,                 # default: MIR_Aligned/frame_mapping.json
#     json_is_zero_based=True,           # your JSON uses 0-based indices
#     out_index="python"                 # keep 0-based in the DataFrame
# )

# print(df.shape)
# print(df.index[:5])              # 0-based frame index
# print(df.filter(like="com1_").head(1))   # peek COM cols if present
# print(df.filter(like="_a1").columns[:9]) # first few kp cols for animal 1
# print(df["camera_frame_sixcam"].head())



merged = merge_pred_with_miniscope(
    rec_path=rec_path,
    nc_key=nc_key,
    dannce_folder=dannce_folder,
    com_folder=None,
    save_h5=False,
    save_csv=False,
)
merged.shape, merged.index[:3]



plot_two_coms_from_pred_df(
    merged,
    smooth_window=5,
    threshold_mm=250.0,         # or None
    out_path=None,               # or "/path/to/MIR_Aligned/two_coms.png"
    title="2social_mini_20240819V1r1_femalebleach_11_48"
)

# below useless, for testing purposes or personal record

In [3]:
import pyarrow.compute as pc
from functools import reduce


table = all_df #combined_df
# Filter mir_generate_param == 0 and sync != 3
# ============================================================================
# FILTERING CONDITIONS
# ============================================================================

# Define your filtering criteria
conditions = [
    pc.equal(table['sync'], '1'),        # Videos are synchronized
    pc.equal(table['com'], '1'),         # Center of mass tracking complete
    # pc.equal(table['dannce'], '1'),    # 3D pose estimation complete
    # pc.equal(table['social'], '0'),    # Solo recordings only (0=solo, 1=social)
    # pc.equal(table['mini_6cam_map'], '1'),  # 6-camera miniscope mapping done
]


filter_mask = reduce(pc.and_, conditions)


# Apply the filter and print the results
filtered_table = table.filter(filter_mask)

# ============================================================================
# DISPLAY RESULTS
# ============================================================================

# Convert to pandas for easier viewing
filtered_df = filtered_table.to_pandas()

# Select meaningful columns for display
display_cols = ['export_dest_rel_path', 'export_dest_full_path', 'social', 'test', 'before_oxytocin', 'after_oxytocin']

print(f"\nFiltered: {len(filtered_df)} recordings")
filtered_df[display_cols]

Filtered: 363 recordings

,export_dest_rel_path,export_dest_full_path,social,test,before_oxytocin,after_oxytocin
0,single/20241024_MC8_S1/,/data/big_rim/sorted_mir_dataset/oct3v1_single...,0,0,0,0
1,single/20241017_VC4_S3/,/data/big_rim/sorted_mir_dataset/oct3v1_single...,0,0,0,0
2,single/20241107_MC7_S3/,/data/big_rim/sorted_mir_dataset/oct3v1_single...,0,0,0,1
3,single/20250212_MC8_S3/,/data/big_rim/sorted_mir_dataset/oct3v1_single...,0,0,0,0
4,single/20250212_MC8_S5/,/data/big_rim/sorted_mir_dataset/oct3v1_single...,0,0,0,0
...,...,...,...,...,...,...
358,oct3v1_beh_only/social/20250514_MC13+UNK16_S1/,/data/big_rim/uploade_ssh_mir_dataset/oct3v1_b...,1,0,0,0
359,oct3v1_beh_only/social/20241231_VC1+MC1_S1/,/data/big_rim/uploade_ssh_mir_dataset/oct3v1_b...,1,0,0,0
360,oct3v1_beh_only/social/20241030_MC10+UNK1_S6/,/data/big_rim/uploade_ssh_mir_dataset/oct3v1_b...,1,0,0,0
361,oct3v1_beh_only/social/20241231_VC6+UNK12_S1/,/data/big_rim/uploade_ssh_mir_dataset/oct3v1_b...,1,0,0,0
362,oct3v1_beh_only/social/20241029_MC10+UNK1_S1/,/data/big_rim/uploade_ssh_mir_dataset/oct3v1_b...,1,0,0,0